### ISSUE TITLE
Sigma argument not used for gray value images?

### ISSUE THREAD

**Issue by jnienh** [DawyD/bm3d-gpu#5]
Hi! Thanks for this great implementation! 
However, I noticed that changing sigma did not change the output when denoising gray scale images. From looking into the code, I think the reason is that the parameter sigma is only actually used if `channels == 3`, while it is initialized to 625 otherwise. I changed it in my local copy of the repository, and it seems to have fixed it, although based on the results I am still not 100% sure I really replaced it with the correct values (from my understanding, `sigma2` should simply be sigma squared, i.e. the variance).

It concerns lines 49-64 in `main_nodisplay.cpp` (I indicate my "fix" as a comment in line 53 (line 5 of the snippet))

```
	//Allocate images
	CImg<unsigned char> image(argv[1]);
	CImg<unsigned char> image2(image.width(), image.height(), 1, channels, 0);
	std::vector<unsigned int> sigma2(channels);
	sigma2[0] = 25 * 25;   // <---    sigma2[0] = sigma * sigma;     
	
	//Convert color image to YCbCr color space
	if (channels == 3)
	{
		image = image.get_channels(0, 2).RGBtoYCbCr();
		//Convert the sigma^2 variance to the YCbCr color space
		long s = sigma * sigma;
		sigma2[0] = ((66l*66l*s + 129l*129l*s + 25l*25l*s) / (256l*256l));
		sigma2[1] = ((38l*38l*s + 74l*74l*s + 112l*112l*s) / (256l*256l)),
		sigma2[2] = ((112l*112l*s + 94l*94l*s + 18l*18l*s) / (256l*256l));
	}
```

It would be great if you could verify the issue and that the fix is correct.

**Comment by MartinKahn** [comment]
Hi - thank you for implementing this on GPU! Has this issue been addressed? I have also tested greyscale images with various settings and the sigma value or "twostep" arguments seem to not make a difference?

**Comment by DawyD** [comment]
Hi,
thanks for reporting the bug. You were right and I've just fixed it.
The "twostep" argument is, on the other hand working as intended. However, because I did not write a proper argument parser, you have to write "twostep" as 5th argument, see the README for the correct usage for grayscale denoising.
